[tools]
go-jsonnet = "latest"

[env]
JSONNET_PATH = "src"

[tasks.build]
description = "Compile Modus themes"
run = "jsonnet src/theme.jsonnet > themes/modus.json"

[tasks.watch]
description = "Watch and compile Modus themes on changes"
run = "mise watch build --watch src"

[tasks.screenshots]
description = "Run a script for making screenshots with all theme variations"
run = "osascript ./scripts/make_screenshots.scpt"
